version: '3.5'

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/src/github.com/masuyu/wkhtmltopdf-api
    command: go run wkhtmltopdf.go
    ports:
      - 1323:1323
